// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require('../04-names/4-names')
const sayHi = require('../05-utils/5-utils')
const data = require('../06-alternative-flavor/6-alternative-flavor')
require('../07-mind-grenade/7-mind-grenade')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)